// Generated by go run ./cmd/contracts -typescript. Do not edit.
export type Money = string
export interface APIEndpoint {
  id: string
  name: string
  description: string
  path_pattern: string
  match_type: string
  methods: (string)[]
  unit_cost: number
  auth_required: boolean
  protocol: string
  metering_unit: string
  example_request: string
  example_response: string
}
export interface APIKey {
  id: string
  name: string
  prefix: string
  scopes: (string)[]
  created_at: string
  last_used: string | null
  expires_at: string | null
  revoked_at: string | null
  raw_key?: string
}
export interface AccountCreated {
  user_id: string
  verification_required?: boolean
}
export interface AccountRequest {
  name: string
}
export interface AdjustmentRequest {
  amount: Money
  direction: string
  reason: string
}
export interface AuditEntry {
  id: string
  actor_id: string
  actor_email: string
  action: string
  target_id: string
  reason: string
  created_at: string
}
export interface ChallengeRequest {
  token: string
  password?: string
}
export interface Credentials {
  email: string
  password: string
  name?: string
  setup_token?: string
}
export interface Customer {
  id: string
  name: string
  email: string
  status: string
  plan_id: string
  balance: Money
  shortfall: Money
  frozen: boolean
  role: string
  email_verified: boolean
  created_at: string
}
export interface CustomerStateRequest {
  status: string
  reason: string
}
export interface EmailRequest {
  email: string
}
export interface ExprValidationResult {
  valid: boolean
  error?: string
  message?: string
}
export interface ExpressionRequest {
  expression: string
  context: string
}
export interface HeaderMatch {
  Name: string
  Value: string
  IsRegex: boolean
  Required: boolean
}
export interface Installation {
  setup_required: boolean
  app_name: string
  currency: string
  top_up_amounts: (string)[]
  paddle_client_token: string
  paddle_sandbox: boolean
}
export interface KeyRequest {
  name: string
  scopes?: (string)[]
  expires_at?: string | null
}
export interface LedgerEntry {
  id: string
  user_id: string
  kind: string
  amount: Money
  balance: Money
  reference: string
  description: string
  created_at: string
}
export interface Message {
  message: string
}
export interface MeteredUsage {
  id: string
  name: string
  path: string
  unit: string
  quantity: number
  requests: number
}
export interface Order {
  id: string
  user_id: string
  provider: string
  amount: Money
  currency: string
  state: string
  provider_id?: string
  checkout_url?: string
  crypto_amount?: string
  crypto_token?: string
  expires_at?: string | null
  created_at: string
}
export interface Overview {
  customers: number
  requests: number
  errors: number
  pending_reservations: number
  wallet_liability: Money
  top_up_volume: Money
}
export interface Pagination {
  total: number
  page: number
  per_page: number
  pages: number
}
export interface PasswordRequest {
  current_password: string
  password: string
}
export interface Plan {
  id: string
  name: string
  description: string
  price: Money
  unit_price: Money
  included_units: number
  rate_limit_per_minute: number
  term_days: number
  is_base: boolean
  enabled: boolean
}
export interface ProviderInfo {
  id: string
  name: string
  crypto: boolean
}
export interface PurchaseRequest {
  plan_id: string
}
export interface ReasonRequest {
  reason: string
}
export interface RenewalRequest {
  auto_renew: boolean
  next_plan_id?: string
}
export interface Reservation {
  plan_id?: string
  rate_limit_per_minute?: number
  id: string
  user_id: string
  key_id: string
  route_id: string
  term_id?: string
  units: number
  quota_units: number
  amount: Money
  unit_price: Money
  state: string
  created_at: string
}
export interface ResolveRequest {
  charge: boolean
  reason: string
}
export interface ReversalRequest {
  amount: Money
  reason: string
}
export interface RouteDraft {
  id: string
  name: string
  path_pattern: string
  match_type: string
  methods: (string)[]
  headers: (HeaderMatch)[]
  host_pattern: string
  host_match_type: string
  upstream_id: string
  path_rewrite: string
  method_override: string
  request_transform: Transform | null
  response_transform: Transform | null
  metering_expr: string
  metering_unit: string
  protocol: string
  unit_cost: number
  auth_required: boolean
}
export interface RouteTestRequest {
  method: string
  path: string
  headers: Record<string, string>
  body: string
  route_id?: string
  draft?: RouteDraft | null
  response?: RouteTestResponse | null
}
export interface RouteTestResponse {
  status: number
  headers: Record<string, string>
  body: string
}
export interface RouteTestResult {
  matched: boolean
  route_name?: string
  route_id?: string
  path_params?: Record<string, string>
  match_reason?: string
  upstream_name?: string
  upstream_url?: string
  transformed_method?: string
  transformed_path?: string
  transformed_headers?: Record<string, string>
  transformed_body?: string
  transformed_query?: string
  response_status?: number
  response_headers?: Record<string, string>
  response_body?: string
  unit_cost: number
  auth_required: boolean
  metering_unit: string
  metering_expr?: string
  metering_sample?: number
  error?: string
}
export interface Session {
  user_id: string
  name: string
  email: string
  role: string
  plan_id: string
  email_verified: boolean
  csrf_token: string
}
export interface Settings {
  values: Record<string, string>
}
export interface Term {
  id: string
  plan_id: string
  plan_name: string
  price: Money
  unit_price: Money
  included_units: number
  used_units: number
  reserved_units: number
  rate_limit_per_minute: number
  starts_at: string
  ends_at: string
}
export interface TopUpRequest {
  amount: Money
  provider: string
}
export interface Transform {
  set_headers?: Record<string, string>
  delete_headers?: (string)[]
  body_expr?: string
  set_query?: Record<string, string>
  delete_query?: (string)[]
}
export interface UpstreamHealth {
  reachable: boolean
  status_code: number
  latency_ms: number
  error?: string
}
export interface UsageDay {
  id: string
  requests: number
  errors: number
  units: number
  latency_ms: number
}
export interface UsageSummary {
  requests: number
  errors: number
  units: number
  spending: Money
  usage_spending: Money
  plan_spending: Money
}
export interface Wallet {
  user_id: string
  balance: Money
  reserved: Money
  available: Money
  shortfall: Money
  frozen: boolean
  currency: string
  auto_renew: boolean
  next_plan_id?: string
  renewal_price?: Money | null
  term?: Term | null
}
