// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/coolqoo/better-apigate",
        "contact": {
            "name": "better-apigate Support",
            "url": "https://github.com/coolqoo/better-apigate/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns OK if the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "status: ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Returns OK if the service is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "status: ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Checks if the service and upstream are ready to handle traffic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "status: ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "status: unhealthy, error: message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the version information for the better-apigate service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Get service version",
                "responses": {
                    "200": {
                        "description": "Version information",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.VersionResponse"
                        }
                    }
                }
            }
        },
        "/{path}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the request, applies rate limiting, forwards to upstream, and records usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Proxy request to upstream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Bearer token (format: Bearer {api_key})",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upstream response"
                    },
                    "401": {
                        "description": "Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "502": {
                        "description": "Upstream error",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the request, applies rate limiting, forwards to upstream, and records usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Proxy request to upstream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Bearer token (format: Bearer {api_key})",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upstream response"
                    },
                    "401": {
                        "description": "Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "502": {
                        "description": "Upstream error",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the request, applies rate limiting, forwards to upstream, and records usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Proxy request to upstream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Bearer token (format: Bearer {api_key})",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upstream response"
                    },
                    "401": {
                        "description": "Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "502": {
                        "description": "Upstream error",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the request, applies rate limiting, forwards to upstream, and records usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Proxy request to upstream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Bearer token (format: Bearer {api_key})",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upstream response"
                    },
                    "401": {
                        "description": "Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "502": {
                        "description": "Upstream error",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Authenticates the request, applies rate limiting, forwards to upstream, and records usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proxy"
                ],
                "summary": "Proxy request to upstream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Bearer token (format: Bearer {api_key})",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Upstream response"
                    },
                    "401": {
                        "description": "Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    },
                    "502": {
                        "description": "Upstream error",
                        "schema": {
                            "$ref": "#/definitions/adapters_http.ErrorResponseBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "adapters_http.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_api_key"
                },
                "message": {
                    "type": "string",
                    "example": "The provided API key is invalid"
                }
            }
        },
        "adapters_http.ErrorResponseBody": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/adapters_http.ErrorDetail"
                }
            }
        },
        "adapters_http.VersionResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "apigate"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key for authentication",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BearerAuth": {
            "description": "Bearer token authentication (format: \"Bearer {api_key}\")",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "better-apigate - API Monetization Proxy",
	Description:      "Self-hosted API monetization solution with authentication, rate limiting, usage metering, and billing.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
