ALTER TABLE usage_events ADD COLUMN route_id TEXT NOT NULL DEFAULT '';
ALTER TABLE usage_events ADD COLUMN metered_value DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE usage_events ADD COLUMN metering_unit TEXT NOT NULL DEFAULT '';
